### ISSUE TITLE
" - " as Album Separator

### ISSUE THREAD

**Issue by nothing2obvi** [Salvoxia/immich-folder-album-creator#77] opened 2024-11-28 21:28 UTC
Hello, I have my album separator set to ` - ` (space dash space), but in Immich, the albums created have a mix of ` - ` (space dash space) and `-` (dash).

Examples:
```
Digital-Graduation
Vacation - Hawaii
```

In some cases, albums are listed twice, using both, with different amounts of assets in them.
```
Scans-Baby Pics-Random (36 items)
Scans - Baby Pics - Random (16 items)
```

How can I fix this? Would it involve starting from scratch, and what would that entail? Thanks!

**Comment by Salvoxia** [comment] 2024-11-28 22:03
Huh, that's a new one, never seen that before.
Preface: For cleaning up, there are two modes: Either delete all albums from Immich, even manually created ones, or only delete albums the script would have created. That way, you might have to play around with the album separator to remove everything.

For cleaning up, you need to set the `MODE`  environment variable to either `CLEANUP`  or `DELETE_ALL`. This will perform a dry-run of cleaning up, only printing the albums it would delete. To actually delete the albums, you also need to set the `DELETE_CONFIRM` environment variable to `1`.

One-shotting these looks like this:
  - Dry-running `CLEANUP`
`docker run -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external" -e MODE="CLEANUP" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`
  - Dry-running `DELETE_ALL`
  `docker run -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external" -e MODE="DELETE_ALL" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`
  - Confirming `CLEANUP`
  `docker run -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external" -e MODE="CLEANUP" -e DELETE_CONFIRM="1" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`
  - Confirming `DELETE_ALL`
   `docker run -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external" -e MODE="DELETE_ALL" -e DELETE_CONFIRM="1" salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`

So far for cleaning up. As to why you have two different variations of album names, I'm not sure.
I suggest to perform dry-runs for album creation after cleaning up so you can confirm whether the album names the script wants to create are what you expect. The settings I saw in your other issue for setting the album separator look fine.
Dry-running album creation looks like this:
   `docker run -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external"  salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`

**Comment by nothing2obvi** [comment] 2024-11-29 03:32
Thank you for all of that. It was helpful to delete all the albums. I couldn't figure out why this problem is happening, so I just went with `_` as the album separator. 

I'll leave this issue open since a solution hasn't been found, but feel free to close it. Thanks again.

**Comment by Salvoxia** [comment] 2024-11-29 04:18
Are you able to reliably reproduce this behavior, i.e. when you performed a dry run for album creation you saw some album names with and some without blanks around the dash?

**Comment by nothing2obvi** [comment] 2024-11-29 06:00
Interestingly, when I ran the dry run, it only listed the top level directories. So it didn't give me an opportunity to see what the album separator would look like. I didn't run the job again to see if it would use the blanks or not. I figured it would cause the same issue since I didn't change anything; all I did was delete all the albums. After trying to figure it out I just made peace with using `_` instead.

So, no, sorry, I haven't tried to reproduce the behavior.

**Comment by Salvoxia** [comment] 2024-11-29 11:53
I tried to reproduce the issue, but was not successful. I tried using both a direct `docker` call on the command line as well as configuring the container using compose using [your setup](https://github.com/Salvoxia/immich-folder-album-creator/issues/76#issuecomment-2505137222) as a template.
Both times it created albums with the separator ` - ` (space dash space).

So I'd be very thankful if you could try to reproduce the issue on your end.
To perform a dry-run while you already have albums, use the following command:
`docker run -e ALBUM_LEVELS="5" -e ALBUM_SEPARATOR=" - " -e FIND_ASSETS_IN_ALBUMS="1" -e API_URL="https://immich.mydomain.com/api/" -e API_KEY="xxxxxxxx" -e ROOT_PATH="/usr/src/app/external"  salvoxia/immich-folder-album-creator:latest /script/immich_auto_album.sh`
or add the `FIND_ASSETS_IN_ALBUMS` environment variable to your compose file and manually trigger a run be attaching to the container and running `./immich_auto_album.sh`.

**Comment by Salvoxia** [comment] 2024-11-29 21:54
I don't have anything else, thank you for trying again. Glad it works, but not happy about not understanding why. But as long as it's not coming back, I'm willing to accept it as a one-time glitch.

**Comment by nothing2obvi** [comment] 2024-12-01 02:05
@Salvoxia 

So I was setting up another Immich instance on another Mac and the same thing happened.

```
Reference-BookStack
Reference-Jellyfin - Avatars
Reference-Jellyfin-Logos
Reference - LubeLogger
```

I'm not certain, but I seem to have success if I run it as a `docker run` command initially, then use the Docker container in Portainer afterward to do it periodically. Btw, I'm using OrbStack instead of Docker Desktop, although OrbStack does use Docker.

**Comment by Salvoxia** [comment] 2024-12-01 10:55
Do you happen to still have access to the container's log files when it created these albums? These might be very helpful.

If not, would you be willing again to try and reproduce it, this time with `LOG_LEVEL` set to `DEBUG`?

**Comment by nothing2obvi** [comment] 2024-12-02 06:05
I'll definitely try to reproduce it after we figure out my other issue :)

**Comment by nothing2obvi** [comment] 2024-12-02 09:11
Ran it again in Portainer. Couldn't reproduce the issue. Weird.

**Comment by Salvoxia** [comment] 2024-12-21 20:04
Closing for now due to non-ability to reproduce.

**Closed by Salvoxia** 2024-12-21 20:04 UTC
